// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	taskmodel "github.com/alexey-y-a/go-taskqueue-microservices/libs/taskmodel"
	gomock "github.com/golang/mock/gomock"
)

// MockQueueServiceClient is a mock of QueueServiceClient interface.
type MockQueueServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockQueueServiceClientMockRecorder
}

// MockQueueServiceClientMockRecorder is the mock recorder for MockQueueServiceClient.
type MockQueueServiceClientMockRecorder struct {
	mock *MockQueueServiceClient
}

// NewMockQueueServiceClient creates a new mock instance.
func NewMockQueueServiceClient(ctrl *gomock.Controller) *MockQueueServiceClient {
	mock := &MockQueueServiceClient{ctrl: ctrl}
	mock.recorder = &MockQueueServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueServiceClient) EXPECT() *MockQueueServiceClientMockRecorder {
	return m.recorder
}

// GetPendingTasks mocks base method.
func (m *MockQueueServiceClient) GetPendingTasks(ctx context.Context, limit int) ([]*taskmodel.Task, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingTasks", ctx, limit)
	ret0, _ := ret[0].([]*taskmodel.Task)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingTasks indicates an expected call of GetPendingTasks.
func (mr *MockQueueServiceClientMockRecorder) GetPendingTasks(ctx, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingTasks", reflect.TypeOf((*MockQueueServiceClient)(nil).GetPendingTasks), ctx, limit)
}

// UpdateTaskStatus mocks base method.
func (m *MockQueueServiceClient) UpdateTaskStatus(ctx context.Context, taskID string, status taskmodel.TaskStatus, errMsg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTaskStatus", ctx, taskID, status, errMsg)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTaskStatus indicates an expected call of UpdateTaskStatus.
func (mr *MockQueueServiceClientMockRecorder) UpdateTaskStatus(ctx, taskID, status, errMsg interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTaskStatus", reflect.TypeOf((*MockQueueServiceClient)(nil).UpdateTaskStatus), ctx, taskID, status, errMsg)
}
